### ISSUE TITLE
SourceCodePro seems to show in black and white?

### ISSUE THREAD

**Issue by didibus** [braver/programmingfonts#102]
Not sure if this is normal, but when trying to preview SourceCodePro, the code becomes black and white. The other fonts don't seem to do that.

**Comment by braver** [comment]
That's odd... I don't have that problem. The font isn't really special and the files aren't that large. Can you show a screenshot, preferably with the browser's console open (for any warnings or errors that might show up there)? Also maybe clear cache and try again?

**Comment by braver** [comment]
Can't reproduce
