### ISSUE TITLE
Aurulent Sans Mono - website unrelated

### ISSUE THREAD

**Issue by micahcochran** [braver/programmingfonts#113]
Current website link for font is unrelated content.  http://delubrum.org/

The original website is in archive.org (not much content about the font):
https://web.archive.org/web/20170925102332/http://delubrum.org/

The font files archive .tgz on that page does not seem to have been captured by archive.org.

Here's a copy someone put on their personal website.
https://www.samiam.org/fonts/other/

There are a few GitHub projects with the files.
https://github.com/search?q=Aurulent+Sans

(DaFont, FontSquirrel, and similar websites also have this font.)

What do you do with an orphaned font?  There doesn't seem to be a clear official place to get the font.

**Comment by braver** [comment]
Oh, good catch. In that case I think I'd prefer to link to [www.fontsquirrel.com](https://www.fontsquirrel.com/fonts/Aurulent-Sans-Mono) as that's a reliable source with careful handling of licenses etc.

**Comment by braver** [comment]
fixed in c8f070614d46799f03646f5439395bce7550c2f2

**Comment by micahcochran** [comment]
Thank you!
