### ISSUE TITLE
monocraft? scientifica?

### ISSUE THREAD

**Issue by jfmc** [braver/programmingfonts#118]
Some nice pixel fonts:

  https://github.com/IdreesInc/Monocraft
  https://github.com/nerdypepper/scientifica

**Comment by cognisent** [comment]
https://github.com/IdreesInc/Monocraft/issues/33

If I get permission there, I'll make a PR to add this here.

**Comment by cognisent** [comment]
Permission granted, PR created.

**Comment by braver** [comment]
scientifica, like monocraft, uses the SIL OFL license so no permission required really. Anyone want to make a PR?

**Comment by cognisent** [comment]
Well, since I did the other one... 😅
