### ISSUE TITLE
Missing Operator

### ISSUE THREAD

**Issue by americanhanko** [braver/programmingfonts#12]
It is a paid font ($199), but very unique and excellent design.

http://www.typography.com/blog/introducing-operator

http://www.typography.com/fonts/operator/overview/

**Comment by americanhanko** [comment]
Obviously there is no way you'd be able to include it since it is indeed a paid font, but it would be cool to include some other paid fonts on the site itself.

**Comment by braver** [comment]
@americanhanko just after they released Operator I got in touch Hoefler & Co to see if some kind of licensing could be arranged, but sadly no. I was able to arrange something for the Input fonts, so perhaps more foundries could be persuaded in the future, we'll just have to look at is case by case.
