### ISSUE TITLE
Zooming the font preview does not update the line number spacing

### ISSUE THREAD

**Issue by qqii** [braver/programmingfonts#126]
![image](https://user-images.githubusercontent.com/6891353/210406056-511e5e20-61cf-49e6-ba19-bc36e858cc15.png)

Nor does it update the selection:

![image](https://user-images.githubusercontent.com/6891353/210406604-deb34503-7566-4313-8a87-06fef850bd1b.png)

The last character has very odd spacing too:

![image](https://user-images.githubusercontent.com/6891353/210406669-d2e223bf-4406-418d-b463-81c4f81c1fa5.png)

This occurs when zooming in and out, and is only resolved by removing and readding all lines > 10.

**Comment by qqii** [comment]
The same seems to occur when changing fonts, or when refreshing with a non default font size.

**Comment by braver** [comment]
By “zooming” you mean increasing the font-size?

**Comment by qqii** [comment]
Yes, I didn't realise that there was a dialog as I have been using `CTRL +`.

**Comment by braver** [comment]
Right, well it looks like there is nothing wrong with our implementation per se, but CodeMirror kinda falls apart above a certain font-size. So I'm not sure there is something we can do about it, I haven't fully investigated that. Additionally we're stuck at CM 5 currently and still need to upgrade to 6. When we're doing that, I'll make a note of also looking at font-size scaling for larger sizes. For now though, we'll just have to live with it I guess (although if someone figures something out a PR is always welcome!).

**Comment by qqii** [comment]
I took a look and I've figured it out! 

I also tried upgrading from CodeMirror `5.58.1` to `5.65.11`, for which there is a [bunch of minor bug fixes](https://codemirror.net/5/doc/releases.html). As seen in my PR (#128) this doesn't fix this issue but nothing broke either.
