### ISSUE TITLE
[REQUEST] Add 'Martian Mono' font

### ISSUE THREAD

**Issue by ghost** [braver/programmingfonts#129]
Free and open-source monospaced font from Evil Martians,
Martian Mono is a monospaced version of the Martian Grotesk font for code style design. It inherits Grotesk’s brutal and eye-catching aesthetics as well as all of its benefits—metrics equilibrium, readability and intelligibility, and convenience for web developers and designers who believe in a systematic approach to design.
LINK: https://github.com/evilmartians/mono

**Comment by braver** [comment]
Thanks! With fonts with this many variants it's always a shame to showcase only regular, but it's good to have it in there nonetheless.
