### ISSUE TITLE
monocraft fails to load

### ISSUE THREAD

**Issue by ipha** [braver/programmingfonts#130]
monocraft is failing to load due to a filename case mismatch. CSS is looking for `monocraft.ttf` but the file in resources is `Monocraft.ttf`

`downloadable font: download failed (font-family: "monocraft" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: https://www.programmingfonts.org/fonts/resources/monocraft/monocraft.ttf`

**Comment by IdreesInc** [comment]
My mistake, will make a PR to fix this now
