### ISSUE TITLE
Add `Comic Mono` font

### ISSUE THREAD

**Issue by hahuutin** [braver/programmingfonts#135]
This is a fork of <ins>**[comic-shanns](https://github.com/shannpersand/comic-shanns)**</ins> with some differences.
You can check here: https://dtinth.github.io/comic-mono-font/

![Screenshot 2023-06-24 094251](https://github.com/braver/programmingfonts/assets/6869015/bffce73a-8027-408c-b5b7-412d359a525a)

**Comment by waldyrious** [comment]
There's also [Serious Sans](https://github.com/kaBeech/serious-sans) which is in turn a fork of Comic Mono. The differences are listed [here](https://github.com/kaBeech/serious-sans#differences-from-comic-mono).

@braver is it OK to track addition of Serious Sans in this issue, or would you rather a new thread be opened?

**Comment by braver** [comment]
Nah, it’s good here. Adding more fonts in one go is a lot more efficient anyway, so once I get around to it I might just as well do a batch.
