### ISSUE TITLE
programmingfonts.org shows generic "empty page" message

### ISSUE THREAD

**Issue by RAnders00** [braver/programmingfonts#14]
This is what http://programmingfonts.org/ looks like for me:

![chrome_2016-12-24_10-14-08](https://cloud.githubusercontent.com/assets/1629196/21466221/c0f83c82-c9c1-11e6-8103-9edd94716df7.png)

**Comment by braver** [comment]
Apparently I had some mis-configured IPv6 entries in my DNS setup, those are gone now and so should this message.
