### ISSUE TITLE
Add font: Reddit Mono (SIL OFL)

### ISSUE THREAD

**Issue by AkshayChn** [braver/programmingfonts#140]
Information we need about new fonts:
- What's it called?
  Reddit Mono
- Where did you find it? Preferably the website of the creator of the font.
  GitHub: https://github.com/reddit/redditsans
  Website: https://redditsans.s-ings.com/
- Where can we download it?
  Here: https://redditsans.s-ings.com/Reddit%20Sans%201.012.zip
- What's the license?
  SIL OFL v1.1

**Comment by braver** [comment]
Hey, that's cool. Thanks!

**Comment by AkshayChn** [comment]
Please see if the year should be corrected to 2023. It is showing 2020 on programmingfonts.org

**Comment by braver** [comment]
I had it at 2023 at first, but the first versions of the GitHub repo are actually from 2020.
