### ISSUE TITLE
Add font: Monaspace Superfamily (SIL OFL)

### ISSUE THREAD

**Issue by AkshayChn** [braver/programmingfonts#142]
Information we need about new fonts:
- What's it called?
  Monaspace (Superfamily)
- Where did you find it? Preferably the website of the creator of the font.
  https://monaspace.githubnext.com
  https://github.com/githubnext/monaspace
- Where can we download it?
  https://github.com/githubnext/monaspace/releases
- What's the license?
  SIL OFL

**Comment by waldyrious** [comment]
Oooh, that texture healing stuff is pretty cool!
