### ISSUE TITLE
Question about Envy Code R

### ISSUE THREAD

**Issue by Finii** [braver/programmingfonts#145]
`Envy Code R` had been added in 2019 after a seemingly solved discussion about the license:

* #46 

![image](https://github.com/braver/programmingfonts/assets/16012374/dc040613-4fc5-469e-95bb-d422e5e8921e)

But then in Summer 2023 is got removed again with

bb7c43bace7 `remove envy code r: license does not allow inclusion`

As far as I can see that was not part of a PR and no further explanation is given.

From the [repository](https://github.com/damieng/envy-code-r) the license does look ok, or not?

![image](https://github.com/braver/programmingfonts/assets/16012374/d6e435e8-660e-4325-9446-5075cabce3a1)

Nerd Fonts has the same font redistributing it with consent from the author.
* https://github.com/ryanoasis/nerd-fonts/issues/1205
* https://github.com/ryanoasis/nerd-fonts/pull/1318

Maybe @braver and/or @damieng has some comment?

**Comment by damieng** [comment]
Yeah I gave permission a while back, not sure why it got removed from there and here.

**Comment by Finii** [comment]
Thanks for clarifying this! Maybe it was by accident because Koen did not see the new OFL license.

**Comment by Finii** [comment]
> why it got removed from there and here

**It** was just removed here at programmingfonts.org

_Edit: Fix typo_

**Comment by braver** [comment]
Riiiight... I think I just got confused about the license. I would normally include the license type in the JSON, and since it wasn't there, nor in the files I had, I figured something got messed up and took the safe route of removing it. But that looks like a mistake now. I'll bring it back and update the license info I have. Thanks guys!
