### ISSUE TITLE
Request: Option to switch on/off line wrap.

### ISSUE THREAD

**Issue by yvvt0379** [braver/programmingfonts#147]
**Is your feature request related to a problem? Please describe.**
none

**Describe the solution you'd like**
Provide an option to switch on/off line wrap.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by braver** [comment]
That doesn't affect the way fonts are rendered. The font-size, line-height, color scheme options do. As does the language option, ensuring you can use code you're used to. But I don't want to add any UI for the code panel otherwise.
