### ISSUE TITLE
Add font: Natural Mono

### ISSUE THREAD

**Issue by pirj** [braver/programmingfonts#152]
Information we need about new fonts:
- What's it called? Natural Mono
- Where did you find it? https://www.1001fonts.com/natural-mono-font.html
- Where can we download it? https://www.1001fonts.com/natural-mono-font.html
- What's the license? SIL OFL

**Comment by braver** [comment]
This is another of those weird free fonts. Who's that creator, where did this font come from, etc.? Is it someone's rainy Sunday project they just uploaded to 1001fonts, or is it actually any good?

**Comment by braver** [comment]
So it's a "Modified version of Noto Sans Mono" according to 1001fonts. Looks like created by Vasily Draigo. Not other information out there. For any SIL OFL fonts anyone can download them, tweak them in something like Fontforge, and upload them to 1001fonts or one of the dozens of sites out there. It looks like that happens a lot, where hobbyists go and make fonts or play around with fonts and publish them. I'm not saying that's what happened here, but that's what it looks like to me.

I like to "curate" the list a little bit. Why does this font exist, how is it different from Noto, who made it? I created a new label to tag new font requests like this one. Maybe we find the info later, or change our mind about it.
