### ISSUE TITLE
Add font: NK57 Monospace

### ISSUE THREAD

**Issue by pirj** [braver/programmingfonts#153]
Information we need about new fonts:
- What's it called? NK57 Monospace
- Where did you find it? https://www.1001fonts.com/nk57-monospace-font.html
- Where can we download it? https://www.1001fonts.com/nk57-monospace-font.html
- What's the license? [Public Domain](https://www.1001fonts.com/licenses/public-domain.html).

**Comment by braver** [comment]
Ok, so this is actually a font created by 1001fonts? [dafont.com](https://www.dafont.com/typodermic-fonts.d1705) claims it's by [typodermic](https://typodermicfonts.com), although Typodermic doesn't list that font. In fact many of the fonts claimed to be by 1001fonts are in fact by Typodermic. What's going on there? 

Aha

> He would proceed to release large portions of his Larabie Fonts library (inasmuch as he could, since some of the designs were derived from freeware that turned out to be copyrighted and thus could not be re-released), along with less successful designs for Typodermic, into the public domain in 2020, 2022 and 2024.
https://en.wikipedia.org/wiki/Ray_Larabie

And NK57 has been released into the public domain: https://typodermicfonts.com/public-domain/ in 2020. So Ray Larabie is the creator, or at least his foundry Typodermic is. 

Not sure how _good_ it actually is, but looks viable for inclusion here.

**Comment by pirj** [comment]
Now I see how interesting this font librarian duty can get!

**Comment by braver** [comment]
FYI, in this document he gives some background on each font, including this one: https://typodermicfonts.com/wp-content/uploads/2024/08/between-the-lines-v1.pdf
