### ISSUE TITLE
Add font: Eirian Regular

### ISSUE THREAD

**Issue by pirj** [braver/programmingfonts#154]
Information we need about new fonts:
- What's it called? Eirian Regular
- Where did you find it? https://www.1001fonts.com/eirian-font.html
- Where can we download it? https://www.1001fonts.com/eirian-font.html
- What's the license? SIL OFL

**Comment by braver** [comment]
This seems to be the source: https://ggbot.itch.io/eirian-font

Looks pretty good! 👍🏻
