### ISSUE TITLE
Add font: DPSDbeyond Regular

### ISSUE THREAD

**Issue by pirj** [braver/programmingfonts#155]
Information we need about new fonts:
- What's it called? DPSDbeyond Regular
- Where did you find it? https://www.1001fonts.com/dpsdbeyond-font.html
- Where can we download it? https://www.1001fonts.com/dpsdbeyond-font.html
- What's the license? SIL OFL

**Comment by braver** [comment]
This might be a better source: https://www.fontsquirrel.com/fonts/dpsdbeyond, or https://backpacker.gr/fonts/11

I'm not even sure it's monospaced? It's also very much a graphical effects display font... but if it's monospaced it could be considered.

**Comment by braver** [comment]
> I'm not even sure it's monospaced

It is, that was in their design brief. It's visually a bit on the interesting side, but why not :)
