### ISSUE TITLE
Add font: sligoil

### ISSUE THREAD

**Issue by pirj** [braver/programmingfonts#157]
Information we need about new fonts:
- What's it called? sligoil
- Where did you find it? https://velvetyne.fr/fonts/sligoil/
- Where can we download it? https://velvetyne.fr/download/?font=sligoil
- What's the license? Custom, but permissive https://velvetyne.fr/about/faq/ (IANAL)

<img width="941" alt="image" src="https://github.com/user-attachments/assets/6040acee-c70f-4b6c-976d-24dbeab23738">

BONUS: Their other monospace fonts are wonderful https://velvetyne.fr/config/keywords/monospace/

Eg [compagnon](https://velvetyne.fr/fonts/compagnon/) (but the 0 O similarity is a bummer)
<img width="981" alt="image" src="https://github.com/user-attachments/assets/6ee5da93-d337-46ac-8a19-12e8caf64b37">

**Comment by braver** [comment]
Of all their fonts sligoil does look like the one most suited for actual day-to-day use (the others are more "display" fonts that are _also_ monospaced). Great find, I'll add it 👍🏻

**Comment by braver** [comment]
The license is SIL OFL by the way.
