### ISSUE TITLE
Add font: DejaVu Markup

### ISSUE THREAD

**Issue by pirj** [braver/programmingfonts#158]
Information we need about new fonts:
- What's it called? DejaVu Markup
- Where did you find it? https://plaintextproject.online/articles/2020/03/03/fonts.html
- Where can we download it? https://online-fonts.com/fonts/dejavu-markup
- What's the license? Public domain

They claim to be better in some way than just the Mono

**Comment by braver** [comment]
Hm, maybe I'm picky but I'm not entirely happy about the source of those fonts. Neither website explains where it came from, and the known source repositories for the DejaVu project don't have a "Markup" font in them.
