### ISSUE TITLE
Possibility to test drive code from other languages

### ISSUE THREAD

**Issue by mnsc** [braver/programmingfonts#16]
As a user not familiar with javascript
I  want to switch the example code to another programming language
So I can see how the most typical constructs in that language behaves in the selected font

**Comment by mnsc** [comment]
Exemple, Fira Code uses ligatures where e.g `->` becomes a cohesive right arrow. This arrow is used heavily in functional languages so an example for f# would be nice.

**Comment by braver** [comment]
Language support in CodeMirror is pretty broad, so it should be pretty easy to add a bunch. However, each language adds javascript to be loaded, so I'd like to make a selection. If I try to add most from this list would you still miss anything?

http://redmonk.com/sogrady/2015/07/01/language-rankings-6-15/

**Comment by braver** [comment]
I added support for pretty much all of the top 20 languages. If anything specific needs to added, it needs to be in this list: https://github.com/codemirror/CodeMirror/tree/master/mode
