### ISSUE TITLE
Add font: Selectric

### ISSUE THREAD

**Issue by pirj** [braver/programmingfonts#162]
Information we need about new fonts:
- What's it called? Selectric
- Where did you find it? https://www.codeproject.com/Articles/30040/Font-Survey-42-of-the-Best-Monospaced-Programming
- Where can we download it? https://www.fonts4free.net/selectric-font.html
- What's the license? ??? Free for personal use

**Comment by braver** [comment]
This is curious. Who or what is ["Paradox 2005"](https://luc.devroye.org/fonts-44671.html)? I'm always a bit hesitant to add fonts that seem to only live on the dozens upon dozens of "free fonts" websites. There is usually no license file (so the claim "free for personal use" cannot be verified), no background information, and the original creators cannot be found. Hopefully we can track down the source of this font.
