### ISSUE TITLE
Add font: *.bpf gorgeous bitmap fonts

### ISSUE THREAD

**Issue by pirj** [braver/programmingfonts#165]
Information we need about new fonts:
- What's it called? numerous
- Where did you find it? https://github.com/Tecate/bitmap-fonts 
- Where can we download it? https://github.com/Tecate/bitmap-fonts/tree/master/bitmap
- What's the license? various: GPL/OFL etc

https://github.com/Tblue/mkttf may be needed to convert to ttf

Some examples below

![image](https://github.com/user-attachments/assets/9e40be6d-329b-41e8-8313-92b209272d4e)

![image](https://github.com/user-attachments/assets/854ffc58-c4a7-4a4e-8404-0662476b6e61)

![image](https://github.com/user-attachments/assets/44edf853-d506-42cd-a70f-c1538b424652)

![image](https://github.com/user-attachments/assets/88f37a17-5bcb-4fd3-b804-43137a4e0dc2)

![image](https://github.com/user-attachments/assets/c5117837-8e8a-4eb8-9238-a84799fddcef)

**Comment by braver** [comment]
I'm afraid this goes the same way as Triskweline and Dina in that the conversions don't work well enough to do justice to the font. Maybe it kind of works in a demo, but not well enough to actually use on a lot of systems. But it's worth trying, because bitmap fonts are soooo cool.
