### ISSUE TITLE
Add font: Triskweline

### ISSUE THREAD

**Issue by pirj** [braver/programmingfonts#167]
Information we need about new fonts:
- What's it called? Triskweline
- Where did you find it? https://vim.fandom.com/wiki/The_perfect_programming_font
- Where can we download it? https://www.netalive.org/tinkering/triskweline/
- What's the license? unspecified 🙈

**Comment by pirj** [comment]
Closing because fon -> ttf is unreliable https://github.com/braver/programmingfonts?tab=readme-ov-file#bitmap-fon-files

**Comment by braver** [comment]
Yes, I really wanted to add this one (and Dina), but those bitmap font files don't work on the web (or on a Mac), and I never found a conversion that actually works (I tried, it looks horrible at all sizes).
