### ISSUE TITLE
Menus with dark theme difficult to read in Chrome

### ISSUE THREAD

**Issue by jdw1996** [braver/programmingfonts#17]
I'm using Firefox 50 and Chrome 55 on Ubuntu 16.04, but I've seen the same issue using Chrome on Windows 7.

When I switch the colour scheme in the test drive to something with a dark background, the menus change colours so that they are easy to read in Firefox, but in Chrome, only the font colour changes, meaning that they are difficult to read. This is easiest to see in screenshots.

Here's Firefox:
![firefox](https://cloud.githubusercontent.com/assets/17225098/22615804/05dd3da6-ea6b-11e6-84cd-650538d7c3fa.png)

And Chrome:
![chrome](https://cloud.githubusercontent.com/assets/17225098/22615806/0c0a5dd0-ea6b-11e6-92c0-ae68130a5462.png)

**Comment by braver** [comment]
Oh, that's just wonderful... I'll have to look into that.

**Comment by braver** [comment]
Think I fixed it. On macOS and iOS the options are left to the OS to style, but apparently on other OS's the browser gets to do some of this itself. Oh the glories of web development.

**Comment by jdw1996** [comment]
It's fixed for me now. Thanks!
