### ISSUE TITLE
Add font: Glean

### ISSUE THREAD

**Issue by pirj** [braver/programmingfonts#171]
Information we need about new fonts:
- What's it called? Glean
- Where did you find it? https://github.com/benwr/glean
- Where can we download it? https://github.com/benwr/glean
- What's the license? GPL 3

[HN thread](https://news.ycombinator.com/item?id=12673368)

Found this in the comments https://int10h.org/oldschool-pc-fonts/fontlist/

Improved [neep](https://github.com/braver/programmingfonts/issues/164):

<img width="635" alt="image" src="https://github.com/user-attachments/assets/39b5dbdf-e25a-454f-9652-fecbdc20ea4c">

<img width="614" alt="image" src="https://github.com/user-attachments/assets/7cf9c3a8-1878-4858-afb1-541f7e88d7bc">

<img width="581" alt="image" src="https://github.com/user-attachments/assets/7aa5698b-75cd-4428-ab4f-33175bae02bd">

**Comment by braver** [comment]
This one also goes on the list of fon/bdf pixel fonts that need conversion.
