### ISSUE TITLE
stop using jquery

### ISSUE THREAD

**Issue by braver** [braver/programmingfonts#19]

**Comment by doomsbuster** [comment]
What are you thinking jquery be replaced with?

**Comment by braver** [comment]
Jquery doesn’t do anything for me that modern api’s can’t also do and dropping it shaves off a bunch of kilobytes. Not high on my priority list though, it works.

**Comment by doomsbuster** [comment]
I was thinking I could pick up one of the issues to address. That’s why I asked before I pick it up.

Thanks,
Ashish Desai
www.ashishdesai.com

**Comment by braver** [comment]
If you really want to contribute something valuable, #18 is the biggest one. Lot's of fonts have multiple weights and there is currently no way to see if that's the case, or to preview those weights.

**Comment by doomsbuster** [comment]
Ok. I'll look it over.

**Comment by braver** [comment]
I’m closing this. Refactoring is a constant, not a particular target all by itself.
