### ISSUE TITLE
Roboto Mono

### ISSUE THREAD

**Issue by tomByrer** [braver/programmingfonts#2]
https://www.google.com/fonts/specimen/Roboto+Mono
http://www.1001freefonts.com/roboto_mono.font
Mono-ified Android Font.
Need a PR?

**Comment by braver** [comment]
Hey, that's new! A PR would be awesome.

**Comment by tomByrer** [comment]
I noticed you use dash-case instead of CamalCase for filenames, so I have renamed all the fonts.
I intend to upload all the variations; I will use the 'light' or 'thin' for comments, & might use 'Medium' instead of 'Bold' or 'Regular'.  Is that OK for you?

Do you make `stylesheet.css`, `screens`, `blog.md`, & `list.md` automatically or manually?

**Comment by braver** [comment]
Om afraid it's all manually (luckily it's mostly an addition here and there). Go ahead and all the weights that make sense to you.

**Comment by braver** [comment]
Oh, you know what, I need to put this in my Atom fonts package as well and the setup is the same. So never mind the PR, it should be up later today.

**Comment by tomByrer** [comment]
Darn, had 90% of the PR finished; just needed the screen shot.  Spent 30 min finding a theme that was close to the one you used before..

**Comment by braver** [comment]
Yes, sorry about that and wasting your time. I ended up having to do three other fonts as well, so... Thanks for the effort anyway, it is really appreciated.
