### ISSUE TITLE
Add oldskool fonts

### ISSUE THREAD

**Issue by braver** [braver/programmingfonts#20]
http://int10h.org/oldschool-pc-fonts/

**Comment by braver** [comment]
Actually, that would be a bit too much. To do it well would almost take another site all by itself. So many fonts and variations! And all of that with so few pixels. 🤯 Such an amazing resource, there are more fonts in there than in this already pretty comprehensive set. That said, they're monospace fonts, and they're cool, but are they "programming fonts"? I'd say no. But. But more people should know that this exists, so I'm keeping this issue open.

**Comment by jengelh** [comment]
>but are they "programming fonts"?

What makes a font a "programming font", anyway? I can think of but one basic requirement:

* The font in question should be usable for paragraphs of natural language (i.e. non-programming) text, too. (This should already suffice in getting rid of most script (e.g. “wedding”), fancy (e.g. “halloween”) and decorative (e.g. “army stencil”) fonts most people would surely agree do not constitute programming fonts.)

I suggest that the programmingfonts site include _one_ font, and that being `MxPlus IBM VGA 9x16`. Indeed a number of variants exist, such as MDA and EGA, but their differences are small, and VGA9x16 is arguably the longest-lived and most ubiquitous one (1987+ per that one encyclopedia) that people have used in the days—and they surely did programming with it, too, be it qbasic or Borlands Turbo IDEs. The Nvidia NV34 chip (2003) shipped with VGA9 too. Lenovo BIOSes (verified with a 2014 model) use ~~something akin to `MxPlus AST PremiumExec`~~ the [EDK2 UEFI LaffStd font](https://inai.de/projects/consoleet), which is more or less “that VGA font” as we know it, once again.

Edit: substitute AST by UEFI, add a link

**Comment by braver** [comment]
Well that makes a lot of sense actually. It’s a good example to include, and that would also add a link to the full collection of old school pc fonts so more people can discover it.

**Comment by waldyrious** [comment]
Interesting, it seems very similar to the classic Fixedsys. Could it be that there's some relationship between them? Here's what [Wikipedia](https://en.wikipedia.org/wiki/Fixedsys) says:

> A smaller CGA version of this font also exists, with some characters bearing a resemblance to the IBM 8x8 [CGA font](https://int10h.org/oldschool-pc-fonts/fontlist/font?ibm_cga#-). The EGA version is nearly identical to the CGA version, only in differing in a small number of characters.

(Link in the quote added by me.)

By the way, the font data [currently says](https://github.com/braver/programmingfonts/blob/eb8ae339e2e7812ec56d22e7f5aba40f5176aa8e/fonts.json#L663) that Fixedsys was created in 1980, but Wikipedia claims it was actually 1984/1985. What gives?

**Comment by jengelh** [comment]
Windows 2.03 has `fontlo.fon` (8x8 cell), `fonthi.fon` (8x12) and `fontsq.fon` (8x16 - the Fixedsys we know today). Indeed the 8x8 one looks like the CGA ROM font, e.g. a rounded 'C'. To be fair, there is only so much you can do with a 8x8 cell, which is why many 8x8 fonts feel the same.

Per https://virtuallyfun.com/2018/08/07/windows-386-v2-03/ , Windows in 640x400x2 CGA appears to have used the 8x12 variant however.

**Comment by braver** [comment]
IBM VGA 9x16 Seems to be helped by having that extra pixel to work with. Several glyphs are less "cramped" than Fixedsys.

The years might be off. Even 1987 for the IBM font was a bit of a guess: wikipedia has that as the first year of IBM PS/2, which the font was created for (apparently). I believe we had one of those at home in the late eighties, but I can't remember anything about it other than Police Quest and Leisure Suit Larry 😄.

So, I don't know where I got 1980 from for Fixedsys. Might have put that in as meaning "the eighties". 84 seems the correct year as per that Wikipedia article, I'll update it.

**Comment by braver** [comment]
By the way, don't you love how the zero in Fixedsys is neither dotted nor slashed, but actually something else completely? It's like an S inside the 0.

<img width="13" alt="Screenshot 2023-07-06 at 17 59 16" src="https://github.com/braver/programmingfonts/assets/2543659/339fb9df-c0ba-4469-ac36-79db6551749e">

**Comment by jengelh** [comment]
>IBM VGA 9x16 Seems to be helped by having that extra pixel to work with. Several glyphs are less "cramped" than Fixedsys.

Fixedsys probably wasn't what triggered VGA going 9x16. MDA (1981) and HGC ('82) already offered 9x14.
What's more important than width however is height, because that influences the (typographical) font weight; though 2 pixels are still 2 pixels, it's what makes Fixedsys look bolder than VGA, and CGA still bolder.
