### ISSUE TITLE
Customized Hack font: HackD

### ISSUE THREAD

**Issue by tri-nga** [braver/programmingfonts#23]
Hello.
I've made a customized version of Hack font, using the alt-hack gliphs.
My own version has: slashed zero, no-slab 1, and a slab i.

would be possible to add it to your programming fonts list ? 
Maybe someone could be interested.
I found Hack through your app :)

thank you

**Comment by braver** [comment]
I try not to add every combination of alternative glyphs, but I do really need to find a way to communicate the alternatives. Something like Input has loads of options. So if you don't mind I'm going to say "won't fix" here and approach it under #24.

**Comment by tri-nga** [comment]
Perfectly fine to me :)
