### ISSUE TITLE
Add IBM Plex Mono

### ISSUE THREAD

**Issue by folknor** [braver/programmingfonts#27]
Apparently, it's used by some developers.
I don't know why, but I was curious after hearing about it, so I opened your magnificent app to look at it, and noticed it wasn't there.

https://github.com/IBM/plex

**Comment by braver** [comment]
@folknor It's already here, under the "Plex Mono" name: http://app.programmingfonts.org/#plex-mono

**Comment by folknor** [comment]
Please excuse my stupidity.
Thank you for the excellent site.

**Comment by braver** [comment]
No problem! 💖
