### ISSUE TITLE
Source Code Pro example code has no syntax coloring

### ISSUE THREAD

**Issue by cpeterso** [braver/programmingfonts#29]
The example code has black text on a dark gray background.

http://app.programmingfonts.org/#source-code-pro

**Comment by braver** [comment]
Works on my machine... 


![screen shot 2019-01-21 at 08 33 10](https://user-images.githubusercontent.com/2543659/51458957-34ff0800-1d57-11e9-8d14-152c1ed3af44.png)

**Comment by cpeterso** [comment]
Sorry! This was user error. 😄 I had an old version of the Source Code Pro font installed from 2012, which caused some conflict with the webfont. Installing a more recent version fixed the problem.
