### ISSUE TITLE
Add keyboard shortcuts for navigation

### ISSUE THREAD

**Issue by ghost** [braver/programmingfonts#30]
I'd like to cycle through fonts quickly until one catches my eye. That's too difficult if I have to keep looking at the list and clicking on the next item. Allow me to next/previous using the arrows, or some keyboard shortcut.

**Comment by braver** [comment]
Great idea!

**Comment by mikecluck** [comment]
I put this together which might help. I like these Vim-like controls but it's easy to switch in other keys.

https://gist.github.com/MCluck90/1cbcbb615eca18466b8be6c7ec003df0

**Comment by braver** [comment]
Thanks guys, that's a great starting point too!
