### ISSUE TITLE
Add font: Consolas

### ISSUE THREAD

**Issue by CameronAavik** [braver/programmingfonts#42]
https://en.wikipedia.org/wiki/Consolas

Consolas is the default font for Visual Studio and I believe the default font for VS Code on Windows, so it would be nice to have it included so people can easily compare with it if they are looking to switch off the default.

**Comment by braver** [comment]
It's not possible for me to add that font (or any other commercial or proprietary font). Want I want to do is add a mode where you can input your the name for any font you like so you can compare it to the others.

**Comment by ThomasG77** [comment]
Unsure but does this change the "game" with Consolas license change to OpenSource e.g https://github.com/PiotrGrochowski/Consolas/ ?

**Comment by braver** [comment]
Sure, it's all about the license. But you can't just dump stuff GitHub and call it open source. That repo has no license information. I'll have to research this to see if it's real, because it looks off to me.

**Comment by ThomasG77** [comment]
It seems you are right e.g https://github.com/PiotrGrochowski/Consolas/issues/1 and https://news.ycombinator.com/item?id=19066586
Let's wait for Microsoft and see.

**Comment by braver** [comment]
Yeah, obviously the guy has no clue: 
https://github.com/PiotrGrochowski/Consolas/issues/1

**Comment by braver** [comment]
Ha:

> Repository unavailable due to DMCA takedown.
