### ISSUE TITLE
Split area for comparison

### ISSUE THREAD

**Issue by KoenDG** [braver/programmingfonts#49]
I was going to try this myself but for some reason I can't get the site to load properly on a local machine. Can't find any instructions.

It just shows everything without any css applied, even after doing the `lessc` step.

I was checking the site and thought to myself I wanted to compare more easily, and a split-screen would seem ideal.

It would be uniquely a vertical split, as adding more than 1 horizontal split would quickly become unreadable.

I would suggest adding a small + icon in the lower left and putting buttons next to the font names, labelled "1", "2" etc...

Perhaps only 1 extra area is usefull?

Those are my thoughts. Any help on how to get the page properly rendering locally?

**Comment by braver** [comment]
> Any help on how to get the page properly rendering locally?

What does it say in the console when you open the inspector?

**Comment by KoenDG** [comment]
Agh, indeed, unresolved filepaths.

https://i.imgur.com/3mfj9Jf.png

Sorry about that, was a bit tired, didn't think to check that.

Did some initial changes to allow creatin a 2nd area, nothing significant. Resizing the codemirror area does not come across as straightforward and it looks like some refactoring will be needed to support the 2 windows next to each other.

I'd personally do 1 single vertical split, having now looked at it.

Can be seen here: https://github.com/braver/programmingfonts/compare/gh-pages...KoenDG:splitwindow

**Comment by braver** [comment]
whoops, this isn't fixed yet

**Comment by KoenDG** [comment]
Ah yeah, I totally forgot about this. And I won't have the time to work on it any time soon. This can be closed.

The idea is still nice though.

**Comment by braver** [comment]
I kinda feel like this would actually add UI, a layer of complexity that doesn't make the UX any better, and a bunch of code... while it is already possible to just have two browser windows.

<img width="1280" alt="Screenshot 2020-10-10 at 23 10 56" src="https://user-images.githubusercontent.com/2543659/95665180-2ae5f400-0b4e-11eb-9266-f3a91cde485d.png">

So, I don't feel like it's worth it really to do something about this issue.
