### ISSUE TITLE
Сhange Anka/Coder font link

### ISSUE THREAD

**Issue by rellikmil** [braver/programmingfonts#58]
This is official and full (https://github.com/loafer-mka/anka-coder-fonts) repositary

**Comment by braver** [comment]
Oh, indeed it is. Good find!

**Comment by rellikmil** [comment]
And you can make which fonts are open source and which are closed?

**Comment by braver** [comment]
Not sure what you mean. We can only use fonts here when the license allows it. It does not have to be open source per se. The license type is registered in the data for this website.
