### ISSUE TITLE
Outsource text examples?

### ISSUE THREAD

**Issue by tomByrer** [braver/programmingfonts#6]
Add these maybe?
https://github.com/source-foundry/text-specimens

**Comment by braver** [comment]
The screenshots are not much work really and I have some specimens set up myself. Most of the time is spent researching the designers etc. I would love automated screenshots, but apparently Chris is making them by hand too.

**Comment by tomByrer** [comment]
> Proposed new Codeface gallery images that will be generated through a scripted approach with Pango/Cairo/Pygments for each typeface

edit: https://github.com/chrissimpkins/codeface/tree/image-scripting/scripts

I was thinking having a more central location for the examples though.

**Comment by braver** [comment]
I'm currently working with codeface to centralise a lot of this stuff. Not sure where it'll take us, but this is happening!
