### ISSUE TITLE
Fantastique sans renders incorrectly

### ISSUE THREAD

**Issue by Lexicality** [braver/programmingfonts#62]
https://app.programmingfonts.org/#fantasque-sans
Left: Your site
Right: My editor
![image](https://user-images.githubusercontent.com/847422/67164691-51c37d00-f375-11e9-82a1-549e37e57de3.png)
If you look at `linenumbers` on the highlighted line you can see every letter has rendered at a different height.

I think https://app.programmingfonts.org/#nanum-gothic-coding may have a similar issue

**Comment by braver** [comment]
What browser and OS are you using?

**Comment by Lexicality** [comment]
Chrome, Windows 10 - though it does the same thing in Firefox

**Comment by braver** [comment]
I presume the web font is based on the otf version, and the ttf version might actually have better hinting for Windows. See also: https://github.com/belluzj/fantasque-sans/issues/115

I have changed the font files, hopefully that works.

**Comment by Lexicality** [comment]
Yup, that seems to have fixed it. Thanks!

**Comment by braver** [comment]
Cool!
