### ISSUE TITLE
add keyboard navigation up/down font list

### ISSUE THREAD

**Issue by surfaceowl** [braver/programmingfonts#63]
#1 - great tool - thank you!  Very helpful to see real code in different fonts easily.

#2 - would be helpful to enable keyboard navigation up and down the font list using the arrow keys, so that users can quickly see different fonts rendered.  This would reduce the amount of mouse navigation and also the time users spend navigating through the font list with their mouse.

**Comment by braver** [comment]
Thanks! 

We've had keyboard navigation for a while, but apparently I inadvertently broke it somewhere down the line. It's back now though: 2c1ff6fc211d4929cdc2d7d3ffa229c41414064a
