### ISSUE TITLE
Add Apple's SF Mono

### ISSUE THREAD

**Issue by slacy** [braver/programmingfonts#66]
I just tried this font and think it's pretty great. 

Available from https://developer.apple.com/fonts/

**Comment by braver** [comment]
It's amazing. IMO it oozes a seemingly effortless excellence, without calling attention to itself, that is quite uncommon in mono space fonts made for code. The entire San Fransisco family is fantastic but the Mono is a stand-out for me (for obvious reasons perhaps :D).
That said, the license doesn't allow me to include it here. Which is understandable, but also a bit sad.
