### ISSUE TITLE
Would love to see Delphi / Object Pascal in the syntax highlighting options

### ISSUE THREAD

**Issue by jimmckeeth** [braver/programmingfonts#74]
I'm willing to help implement it if you point me in the right direction.

**Comment by braver** [comment]
Well it’s CodeMirror, so if there is probably an implementation out there somewhere we can use.

**Comment by zoomlogo** [comment]
@braver 

https://codemirror.net/mode/pascal/
https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.58.1/mode/pascal/pascal.min.js 

See if this works...
