### ISSUE TITLE
Add Iosevka v3.0.0 (and variants?)

### ISSUE THREAD

**Issue by roryokane** [braver/programmingfonts#75]
[Iosevka v3.0.0][v3] was just released. When I test [the app’s current version of Iosevka](https://app.programmingfonts.org/#iosevka) with the test string from those release notes:

    @real fox.quick(h){ *is_brown && it_jumps_over(dogs.lazy) } 0123456789 ABCKRWXYZ

I can see that v3.0.0 looks pretty different. So it should be previewable in Programming Fonts, too.

I’m not sure if any of v3.0.0’s stylistic sets matches the old version completely, and therefore I’m not sure whether the old version should be removed when the new version is added.

The release comes with dozens of variants of the font. The main variant seems to be “[Iosevka][main]”, the one linked at the top left of the table of variants. That would be the best one to let people preview in the app.

I’m not sure of your policy on how significant a variant has to be to be worth previewing in Programming Fonts. If you wanted to include more than one variant, then based on their names and position in the table, I think the most significant variants apart from plain Iosevka would be Iosevka Term, Iosevka Fixed, Iosevka Slab, and Iosevka Curly.

[v3]: https://github.com/be5invis/Iosevka/releases/tag/v3.0.0
[main]: https://github.com/be5invis/Iosevka/releases/download/v3.0.0/ttf-iosevka-3.0.0.zip

**Comment by braver** [comment]
As a rule, I don't include more than one version or variant of a given typeface, unless it's published separately as a spin-off font (and even then it needs to be more than simply slashed vs dotted zeroes). E.g. "fixedsys with ligatures" is basically just fixedsys, but published by someone else who put in the effort and I like to highlight such work.

If you take weights into consideration along with open type features, and that's still ignoring variable fonts, there are simply too many options. Iosevka takes it to an extreme, but even Input has numerous variants. 

So, here I would take that "main variant" as the best expression of the overall design. In the [fonts.json data file](https://github.com/braver/programmingfonts/blob/gh-pages/fonts.json) we could list all variants and at some point figure out a way to expose that. I want to create something in the UI that exposes more information about each font anyway.

**Comment by roryokane** [comment]
The site https://app.programmingfonts.org/ is down… is that expected?

> # 404
>
> There isn't a GitHub Pages site here.

**Comment by braver** [comment]
I’m trying to move it from the sub domain to the apex, not 100% successfully yet 😞
