### ISSUE TITLE
Cartograph is non-free

### ISSUE THREAD

**Issue by TinfoilPancakes** [braver/programmingfonts#76]
The link provided does not allow for a free version to download.

**Comment by braver** [comment]
This is correct. Some non-free fonts are featured on the site. My focus is primarily on featuring the craft and design that is out there for you to use, and I try to find ways to include everything. Here I found the creator willing to allow the site to include this font. 

That said, the site does seem to promise that all fonts are free. While that used to be the case, it’s no longer completely true. I’ll update the text to reflect this and not set incorrect expectations.

Thanks for reporting!
