### ISSUE TITLE
profont example too large (font sizes)

### ISSUE THREAD

**Issue by boneskull** [braver/programmingfonts#8]
Howdy,

ProFont is intended (afaik) for smaller font sizes; 9px and 10px look best (with _no_ anti-aliasing).

Example:

![screenshot](http://content.screencast.com/users/chiller/folders/Jing/media/09b79ac2-3b26-4898-85fe-6253868ca4aa/00000329.png)

ProFont is probably not the only font with a "sweet spot".  Perhaps each should have a "default" size?  Browser zooming may also be unsuitable--perhaps a simple widget to change the size would be appropriate?

Thanks for this app!

**Comment by braver** [comment]
Yeah, there are a few bitmap fonts in there that shouldn't be scaled. And I imagine users would want to see other fonts at different sizes too. This is definitely something I want to add!

**Comment by braver** [comment]
Now features a font-size setting
