### ISSUE TITLE
make the left pane (list of typefaces) resizeable

### ISSUE THREAD

**Issue by polemon** [braver/programmingfonts#80]
Some typefaces have a rather long list of designers (or long names) such that part of the line below the typeface's line gets truncated. Things like the year of publication becomes hidden.
Since the line isn't shown in full length when hovering over it, I usually end up opening dev tools and resizing the pane, such that I can see the entire line.
Would be nice if this worked on the website just like that.

Perhaps just show the entire line as a tooltip or something? Resizing seems to be the best solution to me, though.
![Screenshot from 2020-07-01 21-31-37](https://user-images.githubusercontent.com/2887850/86284080-75b4af00-bbe2-11ea-8460-872e3ed2379f.png)

**Comment by braver** [comment]
Yeah, that design needs some work. Having the year, the styles, _and_ the designers all in there clutters it up quite a bit. I'm thinking about maybe having a little box with more details about the selected typeface. That way you could read all that info, while we keep the list simple.

**Comment by braver** [comment]
I decided to clean up and simplify some things. The info in the list was from before there was any filtering. Now it's easier to find fonts with the characteristics you want. The font style (sans or not) is subtly visualised by the font name being in a sans or serif typeface. And everything is visible in the code pane, that's what it's for. So, that frees up enough space to display all the creators for basically every font. Except for iA Writer Mono of course, but a resizable pane is not the solution for that.
