### ISSUE TITLE
Add some **bold** styles to the syntax highlighting of the pre-populated code snippet

### ISSUE THREAD

**Issue by marlonrichert** [braver/programmingfonts#87]
I use actual **boldface** in my terminal (instead of converting it to bright colors) and it has bothered me that Fira Code's boldface looks kinda fuzzy. I would like to be able to find a programming font with a better boldface.

**Comment by braver** [comment]
The problem here is that we're using code mirror themes and basically none of them apply bold to anything. .. I could make comments bold globally, that would give you something at least?

**Comment by marlonrichert** [comment]
Sure, that would help.
