### ISSUE TITLE
Request: Add Binchotan_Sharp [Binchotan]

### ISSUE THREAD

**Issue by rvklein** [braver/programmingfonts#89]
I've used this as my main system interface and text editor for programming font for years now. It was designed to render well at smaller sizes, has a notably unique style, and the metrics for it fit within half/full em grid spaces like a number of other fonts so it can be supplemented with them to have a mostly appropriate set of compatible fallback glyphs too.

( [https://rvklein.me/proj/binchotan/](https://rvklein.me/proj/binchotan/) )

![Draft sheet rendering at nominal pixel size for further example.](https://user-images.githubusercontent.com/11637786/98193056-4bedfa80-1eea-11eb-946c-e2da38591ec4.png)

Furthermore, if you are missing any of the fonts listed in the comparison table on the page for Binchotan, then I suggest you check them out and consider adding them too.

Anyway, I will appreciate your consideration at the very least. Thank you! -- 🐇

**Comment by rvklein** [comment]
Oh shoot. I don't wanna misrepresent what's actually in the build by showing off the draft sheet. So to note, I do not think that I actually got around to including the smallcaps Latin forms in the current build there. However, the Basic Latin, Fullwidth Forms, and Box Drawing characters as well as the combining diacritics shown should all be included in the build currently listed for download on the project page. Also again, thanks.

**Comment by braver** [comment]
Cool, thanks! That would make font 💯 in the collection. Please review the info in https://github.com/braver/programmingfonts/pull/90/commits/f5af7afc48c74e0c2938913e9606e93b39a3f7ba (PR #90), see if I've got everything correct.
