### ISSUE TITLE
sk-Modernist

### ISSUE THREAD

**Issue by cviebrock** [braver/programmingfonts#9]
I'm not sure if you are taking suggestions for new fonts to add, but I came across this one today which has a monospace variant: 

http://seankanedesign.com/work/sk-modernist

**Comment by braver** [comment]
Thanks, I'm always on the lookout for new stuff. I'm going to check this one out later...

> Bandwidth Limit Exceeded
> The server is temporarily unable to service your request due to the site owner reaching his/her bandwidth limit. Please try again later.

:sunglasses:

**Comment by braver** [comment]
I've had a chance to look at it now, but it doesn't seem to be a monospaced font? Of course any font can be used for programming, but it's a bit much to include _all_ fonts here so I'm limiting it to monospace.

**Comment by cviebrock** [comment]
When you download the zip file, there is a monospaced version in it.

**Comment by braver** [comment]
Oh, I missed that, thanks!

**Comment by braver** [comment]
Alright, it's in!
